import type { Supplier, InventoryLedgerEntry, Transaction, User } from './types';
export const MOCK_USERS: User[] = [
  {
    id: 'user-op-001',
    username: 'operator1',
    password_hash: 'pin123',
    role: 'operator',
    active: true,
    features: ['chat-access'],
    created_at: Date.now(),
  },
  {
    id: 'user-mgr-001',
    username: 'manager1',
    password_hash: 'pass456',
    role: 'manager',
    active: true,
    features: ['chat-access'],
    created_at: Date.now(),
  },
  {
    id: 'user-adm-001',
    username: 'admin1',
    password_hash: 'admin789',
    role: 'admin',
    active: true,
    features: ['chat-access', 'fleet', 'hr'],
    created_at: Date.now(),
  },
  {
    id: 'user-aud-001',
    username: 'auditor1',
    password_hash: 'audit123',
    role: 'auditor',
    active: true,
    features: [],
    created_at: Date.now(),
  },
];
export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-001',
    name: 'Jozi Scrap Metals',
    contact_person: 'John Doe',
    phone_number: '011 123 4567',
    email: 'john@joziscrap.co.za',
    address: '123 Main Reef Rd, Johannesburg, 2001',
    epr_number: 'EPR123/ZA',
    is_weee_compliant: true,
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: 'supp-002',
    name: 'Cape Town Recycling Co.',
    contact_person: 'Jane Smith',
    phone_number: '021 987 6543',
    email: 'jane@ctrecycling.co.za',
    address: '45 Marine Drive, Cape Town, 8001',
    epr_number: 'EPR456/ZA',
    is_weee_compliant: true,
    created_at: Date.now() - 86400000,
    updated_at: Date.now() - 86400000,
  },
];
export const MOCK_INVENTORY_LEDGER: InventoryLedgerEntry[] = [
  {
    id: 'ledger-001',
    supplier_id: 'supp-001',
    material_type: 'Copper Wire',
    weight_kg: 125.5,
    capture_timestamp: Date.now(),
    operator_id: 'user-op-001',
    device_id: 'scale-01',
    is_synced: true,
    created_at: Date.now(),
  },
];
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'trans-001',
    ledger_entry_id: 'ledger-001',
    amount: 7530.00,
    currency: 'ZAR',
    payment_method: 'EFT',
    transaction_timestamp: Date.now(),
    epr_fee: 12.55,
    is_synced: true,
    created_at: Date.now(),
  },
];